# Minimal stub for pygame to reduce diagnostics in the workspace.
# This stub is intentionally small and permissive; it's only to help the editor/type checker.
from typing import Any, Tuple

# module-level members
def init() -> None: ...
def quit() -> None: ...

def get_init() -> bool: ...

class Surface: ...
class Rect: ...

class display: ...
class font: ...
class mixer: ...
class image: ...
class draw: ...
class sprite: ...

# common constants used in the project
SRCALPHA: int
BLEND_RGBA_MULT: int
QUIT: int
KEYDOWN: int
KEYUP: int
K_LEFT: int
K_RIGHT: int
K_UP: int
K_DOWN: int
K_ESCAPE: int
K_RETURN: int

# provide Any to be permissive
__all__ = ["init", "quit", "Surface", "Rect", "display", "font", "mixer", "image", "draw", "sprite"]
